#contributor : Lijunpeng <maillijunpeng@gmail.com>
#name :Makefile for complie Tex source 
# --
qianzhui = $1 #只需定义前缀
objects = $(qianzhui).tex
pdffile: 
	xelatex $(objects)
clean:
	rm $(qianzhui).pdf $(qianzhui).log $(qianzhui).aux
